site_name: Documentación de la Plataforma de Diseminación de datos SNMB-Argentina
theme: material
markdown_extensions: [codehilite]
plugins:
    - pdf-export:
        combined: true
nav:
- Home: index.md
- Usuario:
    - 'Guía rápida': user/quickstart.md
    - 'Configuración de aplicaciones': user/config.md
    - 'Creación de aplicaciones': user/create.md
    - 'Descargas': user/download.md
- Desarrollador:
    - 'Guía rápida': dev/quickstart.md
    - 'Código fuente': dev/source_code.md
    - 'Entorno de desarrollo': dev/environment.md
    - Plugins: dev/plugins.md
    - Aplicaciones: dev/apps.md
    - Migración: dev/migrate.md
    - Publicación: dev/releases.md
    - Contribuir: dev/contribute.md
- Referencia:
    - 'Registro de cambios': ref/changelog.md
    - Plugins: ref/plugins.md
    - Eventos: ref/events.md
    - Licencia: ref/license.md
    - portal.properties: ref/portal-properties.md

