site_name: Geoladris
theme: 'material'
pages:
- Home: index.md
- Usuario:
    - 'Guía rápida': user/quickstart.md
    - 'Configuración de aplicaciones': user/config.md
    - 'Creación de aplicaciones': user/create.md
    - 'Migración': user/migrate.md
- Desarrollador:
    - 'Código fuente': dev/source_code.md
    - 'Guía rápida': dev/quickstart.md
    - Plugins: dev/plugins.md
    - Aplicaciones: dev/apps.md
    - Contribuir: dev/contribute.md
    - 'Desarrollar con Eclipse': dev/eclipse.md
- Referencia:
    - 'Registro de cambios': ref/changelog.md
    - Plugins: ref/plugins.md
    - Eventos: ref/events.md

