site_name: Documentación de la Plataforma de Diseminación de datos SNMB-Argentina
theme: material
markdown_extensions: 
    - codehilite
    - admonition
plugins:
    - pdf-export:
        combined: true    
nav:
- Home: index.md
- Usuario:
    - 'Guía rápida': user/quickstart.md
    - 'Instalación en Ubuntu 18.04': user/install_ubuntu.md
    - 'Configuración de aplicaciones': user/config.md
    - 'Creación de aplicaciones': user/create.md
    - 'Edición del Arbol de capas': user/layer_json_editing.md
    - 'Modificación del Logo e Imagen de la cabecera': user/header_editing.md
    - 'Añadir iconos en las capas': user/add_icons.md
    - 'Descargas': user/download.md
    

- Desarrollador:
    - 'Guía rápida': dev/quickstart.md
    - 'Código fuente': dev/source_code.md
    - 'Entorno de desarrollo': dev/environment.md
    - Plugins: dev/plugins.md
    - Aplicaciones: dev/apps.md
    - Migración: dev/migrate.md
    - Publicación: dev/releases.md
    - Contribuir: dev/contribute.md

- Documentación técnica:
    - 'Diagrama de clases': dev/class_diagram.md
    - 'Diagrama Entidad-Relación': dev/entidad_relacion.md
    - 'Árbol de capas': dev/layers.md

- Referencia:
    - 'Registro de cambios': ref/changelog.md
    - Plugins: ref/plugins.md
    - Eventos: ref/events.md
    - Licencia: ref/license.md
    - portal.properties: ref/portal-properties.md

