site_name: Geoladris
theme: 'material'
markdown_extensions: [codehilite]
pages:
- Home: index.md
- Usuario:
    - 'Guía rápida': user/quickstart.md
    - 'Configuración de aplicaciones': user/config.md
    - 'Creación de aplicaciones': user/create.md
    - 'Descargas': user/download.md
- Desarrollador:
    - 'Guía rápida': dev/quickstart.md
    - 'Código fuente': dev/source_code.md
    - Plugins: dev/plugins.md
    - Aplicaciones: dev/apps.md
    - Migración: dev/migrate.md
    - Publicación: dev/releases.md
    - Contribuir: dev/contribute.md
    - 'Desarrollar con Eclipse': dev/eclipse.md
- Referencia:
    - 'Registro de cambios': ref/changelog.md
    - Plugins: ref/plugins.md
    - Eventos: ref/events.md
    - Licencia: ref/license.md
    - portal.properties: ref/portal-properties.md

